# Generated by Django 5.0.2 on 2024-02-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageGallery',
            new_name='Image',
        ),
    ]
