# Generated by Django 5.0.2 on 2024-02-29 19:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_image_image_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
    ]
