# Generated by Django 5.0.2 on 2024-02-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.review'),
        ),
    ]
