# Generated by Django 5.0.2 on 2024-02-29 22:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
