# Generated by Django 5.0.2 on 2024-03-02 17:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to=api.models.get_upload_path),
            preserve_default=False,
        ),
    ]
