services:
  web:
    build: ./
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - DEBUG=True
  scrapper:
    build: ./
    command: >
      sh -c "python manage.py wait_for_db &&
             python dbScrapper.py"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - MEDIA_ROOT=/app/data/
      - HOSTNAME=http://127.0.0.1:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=qrfeedbackdb
      - POSTGRES_USER=qrfeedbackuser
      - POSTGRES_PASSWORD=qrfeedbackpassword
    ports:
      - 5432:5432

volumes:
  postgres_data:
