# Generated by Django 5.0.2 on 2024-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_review_address_review_tg_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="tg_thread_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
